on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet pack --configuration Release
      - uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: '**/*.nupkg'
